name: open3d-pc
channels:
- conda-forge
- nodefaults
dependencies:
- open3d >=0.19.0,<0.20
- pytest >=8.4.1,<9
- hydra-core >=1.3.2,<2
- ruff >=0.12.4,<0.13
- isort >=6.0.1,<7
- python >=3.11
- pip
- pip:
  - -e .

