version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/debug.log
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8
    delay: True
  
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    maxBytes: 5242880
    backupCount: 3
    encoding: utf8
    delay: True
  
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: logs/error.log
    maxBytes: 5242880
    backupCount: 3
    encoding: utf8
    delay: True

root:
  level: INFO
  handlers: [console, debug_file_handler, info_file_handler, error_file_handler]